### ISSUE TITLE
Mega Man X8 (2004 PC): Crashes on exit

### ISSUE THREAD

**Issue by ViperAcidZX** [samuelgr/Xidi#20] opened 2021-12-11 23:10 UTC
I am noticing that every time I close the PC version of Mega Man X8 (the 2004 PC version, not the MT Framework version in the Legacy Collection), it always causes the game to crash as it closes going by how it always creates ~80 MB crash dumps all the time whenever I quit the game by pressing Alt+F4 or closing it from the title screen. I am using a combination of Xidi v3.1.0 with Hookshot v1.2.0, yet no matter the combination of hooking the game with Hookshot — using the HookshotLauncher or Hookshot.exe — it always crashes on exit instead of properly closing the game. I'm not sure if it also has to do with the No CD executable I'm using to play the game without having to use the disc in the CD drive to play it from the hard drive.

**Comment by samuelgr** [comment] 2021-12-12 22:53
Sorry to hear about this issue. Some questions:

1. Which form of Xidi are you running? WinMM, DInput, DInput8, etc.
1. Can Xidi work without Hookshot for this game? Or does it specifically require that you use Hookshot?
1. Does the crash happen when you run the game without Xidi or Hookshot?
   - Try deleting all the Xidi and Hookshot files, then run the game and see what happens.
1. Does the crash happen when you run the game with Hookshot but without Xidi?
   - Delete the file `Xidi.HookModule.XX.dll` and then run the game with Hookshot.

**Comment by ViperAcidZX** [comment] 2021-12-21 01:39
> Sorry to hear about this issue. Some questions:
> 
> 1. Which form of Xidi are you running? WinMM, DInput, DInput8, etc.
> 2. Can Xidi work without Hookshot for this game? Or does it specifically require that you use Hookshot?
> 3. Does the crash happen when you run the game without Xidi or Hookshot?
>    
>    * Try deleting all the Xidi and Hookshot files, then run the game and see what happens.
> 4. Does the crash happen when you run the game with Hookshot but without Xidi?
>    
>    * Delete the file `Xidi.HookModule.XX.dll` and then run the game with Hookshot.

1. Dinput8; the other two forms do not work whatsoever with this game.
2. It cannot. I've tried other forms and launching the game without Hookshot but the game will not work with Xidi without it.
3. It happens with Hookshot, otherwise the game works fine without any Xidi and/or Hookshot files. 
4. It doesn't but it also doesn't work anymore and my XInput controls remains unchanged.

**Comment by samuelgr** [comment] 2021-12-23 08:06
Thanks for the info. Could you please reproduce the issue with Xidi's logging feature enabled at level 4, then provide the logs here? You should get two log files - one for the hook module and one for dinput8.

**Comment by ViperAcidZX** [comment] 2021-12-23 16:26
Here are the two log files I got when the game crashed on exit with Xidi and Hookshot as directed.

[Xidi_HookModule_MEGAMANX8.EXE_10648.log](https://github.com/samuelgr/Xidi/files/7770399/Xidi_HookModule_MEGAMANX8.EXE_10648.log)

[Xidi_DInput8_MEGAMANX8.EXE_10648.log](https://github.com/samuelgr/Xidi/files/7770401/Xidi_DInput8_MEGAMANX8.EXE_10648.log)

**Comment by samuelgr** [comment] 2021-12-30 02:05
Where is the crash dump located? I tested with the [free trial](https://www.pcgamingwiki.com/wiki/Mega_Man_X8#Demos) version of the game along with Xidi and Hookshot. Xidi works fine but I am unable to locate any crash dumps.

**Comment by ViperAcidZX** [comment] 2022-01-02 05:41
The *.dmp crash dumps appears here for me:

`%localappdata%\CrashDumps`

**Comment by samuelgr** [comment] 2022-01-15 03:19
I identified an issue that causes regular crashes on exit with Xidi v3.1.0 for a small test application due to a threading issue. It is fixed as of commit 3fa8eb58e5ec73a762f5cc3267e04a4fff6a5ae9.

Could you please give this development version of Xidi a try and let me know if the issue is resolved?

[Xidi-v3.1.1-dev.50.0+3fa8eb58.zip](https://github.com/samuelgr/Xidi/files/7874136/Xidi-v3.1.1-dev.50.0%2B3fa8eb58.zip)

**Comment by ViperAcidZX** [comment] 2022-01-18 03:44
I just tried the latest dev build of Xidi and it is able to close Mega Man X8's full version without crashing. Thank you very much for looking into this issue! Would it be possible to mention other games that I may encounter issues with Xidi and/or Hookshot in the future? I have a couple of other older PC games that I've tested that either don't work or have some problems with these wrappers.

**Comment by samuelgr** [comment] 2022-01-18 07:36
Great, I'm glad the issue is resolved with this fix. I am planning to do a release in the not-too-distant future that will include it. As for the other games, please do feel free to file more issues and provide whatever information you have. While I cannot promise to get to all of them, I welcome the opportunity to look into it at very least.

**Comment by samuelgr** [comment] 2022-01-29 23:59
Fix is included in the release of v4.0.0.

**Closed by samuelgr** 2022-01-29 23:59 UTC
Labels: bug
