### ISSUE TITLE
Remap POV-hat as LSTICK 

### ISSUE THREAD

**Issue by Hexaae** [samuelgr/Xidi#5] opened 2019-12-16 02:01 UTC
I've bought an Hori Fighting Stick Mini (XInput device) and found some games that ignore this joystick movements because they are detected as POV-hat, and not as LSTICK for movements :(
Would be handy an additional XInput wrapper to just remap POV-hat to act as LSTICK...

**Comment by samuelgr** [comment] 2020-03-10 01:37
To be investigated for a future version.

**Comment by samuelgr** [comment] 2021-01-25 00:28
Fixed in v2.0.0. Please specify `DigitalGamepad` as the mapper type, and the d-pad will be mapped to X and Y axes.

**Comment by Hexaae** [comment] 2021-04-15 20:47
Mmh, this doesn't seem to work with Jazz Jackrabbit 2 - The Secret Files... I tried everything...
XBox controller + buttons do work, but adding:
dinput.dll
dinput8.dll
winmm.dll
with xidi.ini containing:
```
[Mapper]
Type = DigitalGamepad

[Log]
Enabled = yes
Level = 4
```
does nothing: directions of my Hori Fighting Stick Mini (DPAD) are ignored but buttons work fine.

**Comment by samuelgr** [comment] 2021-05-12 05:18
I have Jazz Jackrabbit 2 so I tested with it as well. A couple of questions:
- The configuration you provided should produce a log file. Could you please upload the log file?
- If you use the Xbox controller to play the game, does the d-pad work? In `DigitalGamepad` mode it should work, but in the default mode it should not.

**Comment by Hexaae** [comment] 2021-05-18 09:10
The only log I've found (nothing on my dekstop) was in \Appdata\Roaming\Jazz2:
https://pastebin.com/vVuNUjNW

No, DPAD of my XBox One BT does not work, only LSTICK.

**Comment by samuelgr** [comment] 2021-06-20 19:06
But Xidi + `DigitalGamepad` does work with other games?

You're using another mod along with Xidi, right? It looks like a different mod might be interfering with Xidi being loaded at all, which is likely why you don't see any Xidi log show up on the desktop. I do not see any of the Xidi modules listed in the log you shared, and I also have v1.2.4 (The Secret Files).

**Comment by Hexaae** [comment] 2021-06-26 22:17
Have to check again but I think so...

**Comment by Hexaae** [comment] 2021-08-22 10:13
Doesn't work. Same with old Pitfall a Mayan Adventure (using winmm.dll browsing into the file with a hex-editor):
I put winmm.dll + xidi.ini containing:
```
[Mapper]
Type = DigitalGamepad

[Log]
Enabled = yes
Level = 4
```
But directions of my Hori Fighting Stick Mini (XINPUT device using DPAD signals) are not detected. Buttons do work.

**Comment by samuelgr** [comment] 2021-09-06 20:11
So just to confirm, the fighting stick works with `DigitalGamepad` in some games, but for Jazz Jackrabbit 2 and Pitfall Mayan Adventure it appears the winmm.dll form of Xidi isn't being loaded at all?

**Comment by Hexaae** [comment] 2021-09-11 13:43
Mmmh, tried again but honestly it doesn't seem to work at all.
What I do is copying dlls from "\Xidi-v2.0.0\x64\" into game/program exe dir, edit Xidi.ini there... but doesn't seem to work. Of course I tried also 32bit dlls but in general seems Xidi isn't loaded on my system (Win 10).
Others like XInputPlus do work fine instead... mmh... what am I doing wrong?

**Comment by Hexaae** [comment] 2021-09-11 14:11
Tested once again with ZXSpin emulator and it's exactly as you said. It also generated the log with ZXSpin, but seems totally ignored from JJ2 for example...

**Comment by samuelgr** [comment] 2021-09-11 19:05
If you have all the required runtimes installed and you tried both the 32-bit versions and 64-bit versions of Xidi (I suspect the 32-bit version is the one you want for these older games), then it might be the case that these games - or some mods you might be using with them - are messing with the standard process for loading winmm.dll, which is why Xidi is not being loaded.

For example, I was able to reproduce the same issue with a modded version of Final Fantasy VII (i.e. it ignores the Xidi winmm.dll file and loads the system version instead), and on the other hand my completely unmodded version of JJ2 works fine with Xidi's winmm.dll file.

I do plan to try to fix the winmm.dll loading problem, which is a separate issue tracked in #18. However, I will close this issue since it seems Xidi + DigitalGamepad does make the fighting stick work in games that are able to load it.

**Closed by samuelgr** 2021-09-11 19:05 UTC
Labels: enhancement
